# -*- coding: utf-8 -*-
"""
Generate no-driver-intervention following outputs using trained BC-GRU model.

This script keeps original CSV columns and row count unchanged.
- Longitudinal acceleration: first ``--warmup_frames`` rows match lead longitudinal
  acceleration; thereafter model predictions from ``max(warmup_frames, seq_len-1)``.
  Rows between warmup and first prediction keep original CSV acceleration.
- ``ego_pos_x``, ``ego_speed`` / ``ego_v_long`` are then updated by forward integrating
  the per-row longitudinal acceleration (x direction).
- Lateral channels are generated by replaying each driver's original residual jitter.
  Optional: ``--lateral_pool_data_dir`` / ``--lateral_pool_driver`` build the pool from
  another driver (e.g. style prototype) while the scenario CSVs still come from ``--data_dir``.
- Lead-vehicle behavior columns stay exactly as recorded in original data.

Batch example: **T12 的「公共场景」指的是 T12 这段驾驶里记录的前车轨迹与世界状态**
（``lead_*``、``distance_headway``、时间轴等），通过把 ``--data_dir`` 固定在 T12 会话目录，
让所有被试在**完全相同的前车行为**下对比；**不是**指共用 T12 训练出来的 GRU 权重。
每个 ``D`` 仍用 ``--model_dir`` 里对应 ``T${D}`` 的纵向模型；横向残差池默认也从
``--data_dir`` 下 segment 构建，因此若目录里只有 T12，横向也会来自 T12。若要横向也个性化，
可另设 ``--lateral_pool_data_dir`` / ``--lateral_pool_driver``。

COMMON_CASE="/home/zwx/driver_model/data/T12/行车/20260421_120610_198_exp1_f"

for i in $(seq 1 20); do
  D="T${i}"
  python /home/zwx/driver_model/train/generate_no_driver_following_outputs.py \
    --data_dir "${COMMON_CASE}" \
    --model_dir "/home/zwx/driver_model/outputs/il_bc_gru_per_driver/${D}_longitudinal_framewin" \
    --out_dir "/home/zwx/driver_model/outputs/personalized_no_driver_common_lead/${D}" \
    --lateral_mode original_jitter \
    --lane_center_y -7.625 \
    --seed 42
done


"""
from __future__ import print_function

import argparse
import csv
import json
import os
import random
import re

import numpy as np
import torch
from torch import nn


def _parse_float(v):
    if v is None:
        return None
    s = str(v).strip()
    if not s:
        return None
    try:
        return float(s)
    except ValueError:
        return None


def discover_following_csvs(data_dir):
    cands = []
    for root, _, files in os.walk(data_dir):
        if "driving_data.csv" not in files:
            continue
        p = root.replace("\\", "/")
        if "pre_familiarization" in p:
            continue
        if "overtaking" in p:
            continue
        if re.search(r"/[^/]*_o(?:/|$)", p):
            continue
        if "_b" in p:
            continue
        if ("following" in p) or re.search(r"/[^/]*_f(?:/|$)", p):
            cands.append(os.path.join(root, "driving_data.csv"))
    return sorted(cands)


def _extract_driver_id(path):
    p = path.replace("\\", "/")
    m = re.search(r"/(T\d+)(?:/|$)", p)
    if m:
        return m.group(1)
    return "UNKNOWN"


def _row_value(row, key):
    if key in row:
        v = _parse_float(row.get(key))
        if v is not None:
            return v
    if key == "ego_v_long":
        return _parse_float(row.get("ego_speed"))
    if key == "ego_a_long":
        return _parse_float(row.get("ego_acceleration"))
    if key == "lead_v_long":
        return _parse_float(row.get("lead_speed"))
    if key == "relative_v_long":
        lv = _row_value(row, "lead_v_long")
        ev = _row_value(row, "ego_v_long")
        if lv is None or ev is None:
            return None
        return lv - ev
    if key == "relative_speed":
        lv = _parse_float(row.get("lead_speed"))
        ev = _parse_float(row.get("ego_speed"))
        if lv is None or ev is None:
            return None
        return lv - ev
    if key == "ttc_valid":
        ttc = _parse_float(row.get("ttc"))
        if ttc is None:
            return 0.0
        return 0.0 if abs(ttc - 999.0) < 1e-6 else 1.0
    if key == "time_headway_valid":
        th = _parse_float(row.get("time_headway"))
        if th is None:
            return 0.0
        return 0.0 if abs(th - 999.0) < 1e-6 else 1.0
    if key in ("ttc", "time_headway"):
        v = _parse_float(row.get(key))
        if v is None:
            return 0.0
        if abs(v - 999.0) < 1e-6:
            return 0.0
        return v
    return None


def _build_driver_lateral_pool(paths, lane_center):
    pool = {}
    for fp in paths:
        driver = _extract_driver_id(fp)
        vals_y = []
        vals_yaw = []
        vals_steer = []
        with open(fp, "r", encoding="utf-8") as f:
            for r in csv.DictReader(f):
                y = _parse_float(r.get("ego_pos_y"))
                yaw = _parse_float(r.get("ego_yaw"))
                steer = _parse_float(r.get("steer"))
                if y is not None:
                    vals_y.append(y - lane_center)
                if yaw is not None:
                    vals_yaw.append(yaw)
                if steer is not None:
                    vals_steer.append(steer)
        if not vals_y:
            continue
        yaw_base = float(np.median(vals_yaw)) if vals_yaw else 0.0
        steer_base = float(np.median(vals_steer)) if vals_steer else 0.0
        yaw_res = [v - yaw_base for v in vals_yaw] if vals_yaw else [0.0]
        steer_res = [v - steer_base for v in vals_steer] if vals_steer else [0.0]
        entry = pool.setdefault(
            driver, {"y_res": [], "yaw_res": [], "steer_res": [], "source_files": 0}
        )
        entry["y_res"].extend(vals_y)
        entry["yaw_res"].extend(yaw_res)
        entry["steer_res"].extend(steer_res)
        entry["source_files"] += 1
    return pool


def _sample_with_wrap(values, n, rng):
    if not values:
        return [0.0] * n
    if len(values) == 1:
        return [values[0]] * n
    start = rng.randint(0, len(values) - 1)
    out = []
    for i in range(n):
        out.append(values[(start + i) % len(values)])
    return out


def _moving_average(values, window):
    if window <= 1 or not values:
        return list(values)
    if window % 2 == 0:
        window += 1
    half = window // 2
    out = []
    n = len(values)
    for i in range(n):
        lo = max(0, i - half)
        hi = min(n, i + half + 1)
        out.append(sum(values[lo:hi]) / float(hi - lo))
    return out


def _lead_longitudinal_accel(row):
    v = _parse_float(row.get("lead_a_long"))
    if v is not None:
        return v
    v = _parse_float(row.get("lead_acceleration"))
    return v if v is not None else 0.0


def _original_ego_long_accel(row):
    v = _parse_float(row.get("ego_a_long"))
    if v is not None:
        return v
    v = _parse_float(row.get("ego_acceleration"))
    return v if v is not None else 0.0


def _integrate_longitudinal_x(rows, distance_offset):
    """Forward-integrate ego_pos_x, ego_speed, ego_v_long from per-row longitudinal acc."""
    if not rows:
        return
    n = len(rows)
    ts = [_parse_float(r.get("timestamp")) for r in rows]
    acc = [_original_ego_long_accel(r) for r in rows]
    x0 = _parse_float(rows[0].get("ego_pos_x"))
    v0 = _row_value(rows[0], "ego_v_long")
    if v0 is None:
        v0 = _parse_float(rows[0].get("ego_speed"))
    if x0 is None:
        x0 = 0.0
    if v0 is None:
        v0 = 0.0
    x = [x0]
    v = [v0]
    for i in range(1, n):
        dt = 0.0
        if ts[i] is not None and ts[i - 1] is not None:
            dt = max(0.0, ts[i] - ts[i - 1])
        a = acc[i - 1]
        vn = v[-1] + a * dt
        xn = x[-1] + v[-1] * dt + 0.5 * a * dt * dt
        v.append(vn)
        x.append(xn)
    for i in range(n):
        sx = "{:.6f}".format(x[i])
        sv = "{:.6f}".format(v[i])
        rows[i]["ego_pos_x"] = sx
        if "ego_v_long" in rows[i]:
            rows[i]["ego_v_long"] = sv
        rows[i]["ego_speed"] = sv
        lv = _parse_float(rows[i].get("lead_speed"))
        if lv is not None:
            rs = lv - v[i]
            if "relative_speed" in rows[i]:
                rows[i]["relative_speed"] = "{:.6f}".format(rs)
            if "relative_v_long" in rows[i]:
                rows[i]["relative_v_long"] = "{:.6f}".format(rs)
        if distance_offset is not None:
            lx = _parse_float(rows[i].get("lead_pos_x"))
            if lx is not None:
                rows[i]["distance_headway"] = "{:.6f}".format(
                    abs(x[i] - lx) + distance_offset
                )
        if "ego_jerk" in rows[i]:
            if i == 0:
                rows[i]["ego_jerk"] = "{:.6f}".format(0.0)
            elif ts[i] is not None and ts[i - 1] is not None:
                dt = max(1e-9, ts[i] - ts[i - 1])
                j = (acc[i] - acc[i - 1]) / dt
                rows[i]["ego_jerk"] = "{:.6f}".format(j)


def _smooth_lateral_if_needed(y_res, yaw_res, steer_res, limit_abs, smooth_window):
    """Replay the driver's original lateral residuals, but damp unsafe swings.

    If the lateral residual exceeds the configured fraction of lane width, smooth the
    residual sequence and clip it to the limit so generated trajectories stay near the lane center.
    """
    if not y_res:
        return y_res, yaw_res, steer_res, "driver_residual_pool"
    if max(abs(v) for v in y_res) <= limit_abs:
        return y_res, yaw_res, steer_res, "driver_residual_pool"

    y_sm = _moving_average(y_res, smooth_window)
    yaw_sm = _moving_average(yaw_res, smooth_window)
    steer_sm = _moving_average(steer_res, smooth_window)
    y_sm = [max(-limit_abs, min(limit_abs, v)) for v in y_sm]
    return y_sm, yaw_sm, steer_sm, "driver_residual_pool_smoothed_limited"


def _build_feature_rows(rows, features):
    ts = [_parse_float(r.get("timestamp")) for r in rows]
    feat_rows = []
    for i, r in enumerate(rows):
        fv = []
        ok = True
        for k in features:
            if k == "dt_prev":
                if i == 0:
                    v = 0.0
                else:
                    t0 = ts[i - 1]
                    t1 = ts[i]
                    if t0 is None or t1 is None:
                        v = None
                    else:
                        v = max(0.0, t1 - t0)
            else:
                v = _row_value(r, k)
            if v is None:
                ok = False
                break
            fv.append(v)
        if ok:
            feat_rows.append(np.asarray(fv, dtype=np.float32))
        else:
            feat_rows.append(None)
    return feat_rows


class BCGRU(nn.Module):
    def __init__(self, input_dim, hidden_dim, num_layers, dropout, output_dim):
        super(BCGRU, self).__init__()
        self.gru = nn.GRU(
            input_size=input_dim,
            hidden_size=hidden_dim,
            num_layers=num_layers,
            batch_first=True,
            dropout=dropout if num_layers > 1 else 0.0,
        )
        self.head = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, output_dim),
        )

    def forward(self, x):
        out, _ = self.gru(x)
        h = out[:, -1, :]
        return self.head(h)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data_dir", type=str, default="/home/zwx/driver_model/data")
    ap.add_argument(
        "--model_dir",
        type=str,
        default="/home/zwx/driver_model/outputs/il_bc_gru_gap04",
    )
    ap.add_argument(
        "--out_dir",
        type=str,
        default="/home/zwx/driver_model/outputs/following_no_driver_bc",
    )
    ap.add_argument("--lane_center_y", type=float, default=-7.625)
    ap.add_argument("--lane_width", type=float, default=3.75)
    ap.add_argument(
        "--lateral_jitter_limit_ratio",
        type=float,
        default=0.25,
        help="Smooth/limit lateral residuals when abs(residual) exceeds this fraction of lane width",
    )
    ap.add_argument(
        "--lateral_smooth_window",
        type=int,
        default=11,
        help="Moving-average window used when lateral residuals exceed the limit",
    )
    ap.add_argument("--lateral_mode", type=str, default="original_jitter")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument(
        "--warmup_frames",
        type=int,
        default=20,
        help="First N rows: set ego longitudinal acceleration to match lead; model starts at max(warmup_frames, seq_len-1).",
    )
    ap.add_argument("--device", type=str, default="auto")
    ap.add_argument("--max_files", type=int, default=0)
    ap.add_argument(
        "--lateral_pool_data_dir",
        type=str,
        default="",
        help="If set, build lateral residual pool only from segment_*.csv under this tree (default: same as --data_dir).",
    )
    ap.add_argument(
        "--lateral_pool_driver",
        type=str,
        default="",
        help="If set, restrict lateral pool to this driver id (e.g. style prototype); jitter no longer uses the scenario path's driver id.",
    )
    args = ap.parse_args()

    report_path = os.path.join(args.model_dir, "train_report.json")
    meta_path = os.path.join(args.model_dir, "model_meta.json")
    model_path = os.path.join(args.model_dir, "best_model.pt")
    with open(report_path, "r", encoding="utf-8") as f:
        report = json.load(f)
    with open(meta_path, "r", encoding="utf-8") as f:
        meta = json.load(f)

    features = list(meta["features"])
    targets = list(meta["targets"])
    seq_len = int(meta["seq_len"])
    feat_mean = np.asarray(report["feature_mean"], dtype=np.float32)
    feat_std = np.asarray(report["feature_std"], dtype=np.float32)
    feat_std = np.where(feat_std < 1e-6, 1.0, feat_std)

    if args.device == "auto":
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    else:
        device = torch.device(args.device)

    model = BCGRU(
        input_dim=len(features),
        hidden_dim=int(meta["hidden_dim"]),
        num_layers=int(meta["num_layers"]),
        dropout=0.1,
        output_dim=len(targets),
    ).to(device)
    model.load_state_dict(torch.load(model_path, map_location=device))
    model.eval()

    scenario_paths = discover_following_csvs(args.data_dir)
    if args.max_files and args.max_files > 0:
        scenario_paths = scenario_paths[: args.max_files]
    pool_root = args.lateral_pool_data_dir.strip() or args.data_dir
    pool_paths = discover_following_csvs(pool_root)
    lat_drv = args.lateral_pool_driver.strip()
    if lat_drv:
        pool_paths = [p for p in pool_paths if _extract_driver_id(p) == lat_drv]
    if not pool_paths and lat_drv and args.lateral_mode == "original_jitter":
        print(
            "[WARN] lateral_pool_driver={}: no segment CSVs under {}; lateral jitter may be empty.".format(
                lat_drv, pool_root
            )
        )
    os.makedirs(args.out_dir, exist_ok=True)
    lateral_pool = _build_driver_lateral_pool(pool_paths, args.lane_center_y)

    summary = []
    for fp in scenario_paths:
        rel = os.path.relpath(fp, args.data_dir).replace("\\", "/")
        out_fp = os.path.join(args.out_dir, rel)
        out_parent = os.path.dirname(out_fp)
        if not os.path.isdir(out_parent):
            os.makedirs(out_parent)

        with open(fp, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            fieldnames = list(reader.fieldnames or [])
            rows = list(reader)
        if not fieldnames or not rows:
            continue
        for k in targets:
            if k not in fieldnames:
                fieldnames.append(k)
        if "ego_a_long" in targets and "ego_acceleration" not in fieldnames:
            fieldnames.append("ego_acceleration")
        if "ego_acceleration" in targets and "ego_a_long" not in fieldnames:
            fieldnames.append("ego_a_long")

        ex0 = _parse_float(rows[0].get("ego_pos_x"))
        lx0 = _parse_float(rows[0].get("lead_pos_x"))
        dh0 = _parse_float(rows[0].get("distance_headway"))
        distance_offset = None
        if ex0 is not None and lx0 is not None and dh0 is not None:
            distance_offset = dh0 - abs(ex0 - lx0)

        orig_long_acc = [_original_ego_long_accel(r) for r in rows]
        first_model_i = max(args.warmup_frames, seq_len - 1)
        for i in range(first_model_i):
            la = (
                _lead_longitudinal_accel(rows[i])
                if i < args.warmup_frames
                else orig_long_acc[i]
            )
            la_s = "{:.6f}".format(la)
            if "ego_a_long" in rows[i]:
                rows[i]["ego_a_long"] = la_s
            if "ego_acceleration" in rows[i]:
                rows[i]["ego_acceleration"] = la_s

        feat_rows = _build_feature_rows(rows, features)

        n_pred = 0
        for i in range(len(rows)):
            if i < first_model_i:
                continue
            window = feat_rows[i - seq_len + 1 : i + 1]
            if any(v is None for v in window):
                continue
            x = np.stack(window)
            x = (x - feat_mean) / feat_std
            xt = torch.from_numpy(x).unsqueeze(0).to(device)
            with torch.no_grad():
                yp = model(xt).cpu().numpy()[0]
            for j, k in enumerate(targets):
                rows[i][k] = "{:.6f}".format(float(yp[j]))
                if k == "ego_a_long" and "ego_acceleration" in rows[i]:
                    rows[i]["ego_acceleration"] = "{:.6f}".format(float(yp[j]))
                elif k == "ego_acceleration" and "ego_a_long" in rows[i]:
                    rows[i]["ego_a_long"] = "{:.6f}".format(float(yp[j]))
            n_pred += 1

        _integrate_longitudinal_x(rows, distance_offset)

        if args.lateral_mode == "original_jitter":
            lat_id = lat_drv or _extract_driver_id(fp)
            p = lateral_pool.get(lat_id, {})
            if not p.get("y_res") and lat_id != _extract_driver_id(fp):
                p = lateral_pool.get(_extract_driver_id(fp), {})
            rng = random.Random(args.seed + abs(hash(rel)) % 1000003)
            y_res = _sample_with_wrap(p.get("y_res", []), len(rows), rng)
            yaw_res = _sample_with_wrap(p.get("yaw_res", []), len(rows), rng)
            steer_res = _sample_with_wrap(p.get("steer_res", []), len(rows), rng)
            lateral_limit = args.lane_width * args.lateral_jitter_limit_ratio
            y_res, yaw_res, steer_res, lateral_source = _smooth_lateral_if_needed(
                y_res,
                yaw_res,
                steer_res,
                lateral_limit,
                args.lateral_smooth_window,
            )
            for i in range(len(rows)):
                rows[i]["ego_pos_y"] = "{:.6f}".format(args.lane_center_y + y_res[i])
                if "ego_yaw" in rows[i]:
                    rows[i]["ego_yaw"] = "{:.6f}".format(yaw_res[i])
                if "steer" in rows[i]:
                    rows[i]["steer"] = "{:.6f}".format(steer_res[i])
        else:
            lateral_source = "original_rows"

        with open(out_fp, "w", encoding="utf-8", newline="") as f:
            w = csv.DictWriter(f, fieldnames=fieldnames)
            w.writeheader()
            for r in rows:
                w.writerow(r)

        summary.append(
            {
                "source_file": rel,
                "out_file": os.path.relpath(out_fp, args.out_dir).replace("\\", "/"),
                "n_rows": str(len(rows)),
                "n_pred_rows": str(n_pred),
            "driver_id": _extract_driver_id(fp),
            "lateral_pool_driver": lat_drv,
            "lateral_source": lateral_source,
            }
        )

    sum_fp = os.path.join(args.out_dir, "generation_summary.csv")
    with open(sum_fp, "w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(
            f,
            fieldnames=[
                "source_file",
                "out_file",
                "n_rows",
                "n_pred_rows",
                "driver_id",
                "lateral_pool_driver",
                "lateral_source",
            ],
        )
        w.writeheader()
        for r in summary:
            w.writerow(r)

    print("[OK] generated files:", len(summary))
    print("[OK] summary:", sum_fp)


if __name__ == "__main__":
    main()

