# -*- coding: utf-8 -*-
"""
Generate no-driver-intervention following outputs using trained BC-GRU model.

This script keeps original CSV columns and row count unchanged.
- Longitudinal outputs are replaced by model predictions.
- Lateral channels are generated by replaying each driver's original residual jitter.
- Lead-vehicle behavior columns stay exactly as recorded in original data.
"""
from __future__ import print_function

import argparse
import csv
import json
import os
import random
import re

import numpy as np
import torch
from torch import nn


def _parse_float(v):
    if v is None:
        return None
    s = str(v).strip()
    if not s:
        return None
    try:
        return float(s)
    except ValueError:
        return None


def discover_following_csvs(data_dir):
    cands = []
    for root, _, files in os.walk(data_dir):
        if "driving_data.csv" not in files:
            continue
        p = root.replace("\\", "/")
        if "pre_familiarization" in p:
            continue
        if "overtaking" in p:
            continue
        if re.search(r"/[^/]*_o(?:/|$)", p):
            continue
        if "_b" in p:
            continue
        if ("following" in p) or re.search(r"/[^/]*_f(?:/|$)", p):
            cands.append(os.path.join(root, "driving_data.csv"))
    return sorted(cands)


def _extract_driver_id(path):
    p = path.replace("\\", "/")
    m = re.search(r"/(T\d+)(?:/|$)", p)
    if m:
        return m.group(1)
    return "UNKNOWN"


def _row_value(row, key):
    if key in row:
        v = _parse_float(row.get(key))
        if v is not None:
            return v
    if key == "relative_speed":
        lv = _parse_float(row.get("lead_speed"))
        ev = _parse_float(row.get("ego_speed"))
        if lv is None or ev is None:
            return None
        return lv - ev
    if key == "ttc_valid":
        ttc = _parse_float(row.get("ttc"))
        if ttc is None:
            return 0.0
        return 0.0 if abs(ttc - 999.0) < 1e-6 else 1.0
    if key == "time_headway_valid":
        th = _parse_float(row.get("time_headway"))
        if th is None:
            return 0.0
        return 0.0 if abs(th - 999.0) < 1e-6 else 1.0
    if key in ("ttc", "time_headway"):
        v = _parse_float(row.get(key))
        if v is None:
            return 0.0
        if abs(v - 999.0) < 1e-6:
            return 0.0
        return v
    return None


def _build_driver_lateral_pool(paths, lane_center):
    pool = {}
    for fp in paths:
        driver = _extract_driver_id(fp)
        vals_y = []
        vals_yaw = []
        vals_steer = []
        with open(fp, "r", encoding="utf-8") as f:
            for r in csv.DictReader(f):
                y = _parse_float(r.get("ego_pos_y"))
                yaw = _parse_float(r.get("ego_yaw"))
                steer = _parse_float(r.get("steer"))
                if y is not None:
                    vals_y.append(y - lane_center)
                if yaw is not None:
                    vals_yaw.append(yaw)
                if steer is not None:
                    vals_steer.append(steer)
        if not vals_y:
            continue
        yaw_base = float(np.median(vals_yaw)) if vals_yaw else 0.0
        steer_base = float(np.median(vals_steer)) if vals_steer else 0.0
        yaw_res = [v - yaw_base for v in vals_yaw] if vals_yaw else [0.0]
        steer_res = [v - steer_base for v in vals_steer] if vals_steer else [0.0]
        entry = pool.setdefault(
            driver, {"y_res": [], "yaw_res": [], "steer_res": [], "source_files": 0}
        )
        entry["y_res"].extend(vals_y)
        entry["yaw_res"].extend(yaw_res)
        entry["steer_res"].extend(steer_res)
        entry["source_files"] += 1
    return pool


def _sample_with_wrap(values, n, rng):
    if not values:
        return [0.0] * n
    if len(values) == 1:
        return [values[0]] * n
    start = rng.randint(0, len(values) - 1)
    out = []
    for i in range(n):
        out.append(values[(start + i) % len(values)])
    return out


def _build_feature_rows(rows, features):
    ts = [_parse_float(r.get("timestamp")) for r in rows]
    feat_rows = []
    for i, r in enumerate(rows):
        fv = []
        ok = True
        for k in features:
            if k == "dt_prev":
                if i == 0:
                    v = 0.0
                else:
                    t0 = ts[i - 1]
                    t1 = ts[i]
                    if t0 is None or t1 is None:
                        v = None
                    else:
                        v = max(0.0, t1 - t0)
            else:
                v = _row_value(r, k)
            if v is None:
                ok = False
                break
            fv.append(v)
        if ok:
            feat_rows.append(np.asarray(fv, dtype=np.float32))
        else:
            feat_rows.append(None)
    return feat_rows


class BCGRU(nn.Module):
    def __init__(self, input_dim, hidden_dim, num_layers, dropout, output_dim):
        super(BCGRU, self).__init__()
        self.gru = nn.GRU(
            input_size=input_dim,
            hidden_size=hidden_dim,
            num_layers=num_layers,
            batch_first=True,
            dropout=dropout if num_layers > 1 else 0.0,
        )
        self.head = nn.Sequential(
            nn.Linear(hidden_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, output_dim),
        )

    def forward(self, x):
        out, _ = self.gru(x)
        h = out[:, -1, :]
        return self.head(h)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data_dir", type=str, default="/home/zwx/driver_model/data")
    ap.add_argument(
        "--model_dir",
        type=str,
        default="/home/zwx/driver_model/outputs/il_bc_gru_gap04",
    )
    ap.add_argument(
        "--out_dir",
        type=str,
        default="/home/zwx/driver_model/outputs/following_no_driver_bc",
    )
    ap.add_argument("--lane_center_y", type=float, default=-7.625)
    ap.add_argument("--lateral_mode", type=str, default="original_jitter")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--device", type=str, default="auto")
    ap.add_argument("--max_files", type=int, default=0)
    args = ap.parse_args()

    report_path = os.path.join(args.model_dir, "train_report.json")
    meta_path = os.path.join(args.model_dir, "model_meta.json")
    model_path = os.path.join(args.model_dir, "best_model.pt")
    with open(report_path, "r", encoding="utf-8") as f:
        report = json.load(f)
    with open(meta_path, "r", encoding="utf-8") as f:
        meta = json.load(f)

    features = list(meta["features"])
    targets = list(meta["targets"])
    seq_len = int(meta["seq_len"])
    feat_mean = np.asarray(report["feature_mean"], dtype=np.float32)
    feat_std = np.asarray(report["feature_std"], dtype=np.float32)
    feat_std = np.where(feat_std < 1e-6, 1.0, feat_std)

    if args.device == "auto":
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    else:
        device = torch.device(args.device)

    model = BCGRU(
        input_dim=len(features),
        hidden_dim=int(meta["hidden_dim"]),
        num_layers=int(meta["num_layers"]),
        dropout=0.1,
        output_dim=len(targets),
    ).to(device)
    model.load_state_dict(torch.load(model_path, map_location=device))
    model.eval()

    paths = discover_following_csvs(args.data_dir)
    if args.max_files and args.max_files > 0:
        paths = paths[: args.max_files]
    os.makedirs(args.out_dir, exist_ok=True)
    lateral_pool = _build_driver_lateral_pool(paths, args.lane_center_y)

    summary = []
    for fp in paths:
        rel = os.path.relpath(fp, args.data_dir).replace("\\", "/")
        out_fp = os.path.join(args.out_dir, rel)
        out_parent = os.path.dirname(out_fp)
        if not os.path.isdir(out_parent):
            os.makedirs(out_parent)

        with open(fp, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            fieldnames = list(reader.fieldnames or [])
            rows = list(reader)
        if not fieldnames or not rows:
            continue

        feat_rows = _build_feature_rows(rows, features)

        n_pred = 0
        for i in range(len(rows)):
            if i < seq_len - 1:
                continue
            window = feat_rows[i - seq_len + 1 : i + 1]
            if any(v is None for v in window):
                continue
            x = np.stack(window)
            x = (x - feat_mean) / feat_std
            xt = torch.from_numpy(x).unsqueeze(0).to(device)
            with torch.no_grad():
                yp = model(xt).cpu().numpy()[0]
            for j, k in enumerate(targets):
                rows[i][k] = "{:.6f}".format(float(yp[j]))
            n_pred += 1

        if args.lateral_mode == "original_jitter":
            driver = _extract_driver_id(fp)
            p = lateral_pool.get(driver, {})
            rng = random.Random(args.seed + abs(hash(rel)) % 1000003)
            y_res = _sample_with_wrap(p.get("y_res", []), len(rows), rng)
            yaw_res = _sample_with_wrap(p.get("yaw_res", []), len(rows), rng)
            steer_res = _sample_with_wrap(p.get("steer_res", []), len(rows), rng)
            for i in range(len(rows)):
                rows[i]["ego_pos_y"] = "{:.6f}".format(args.lane_center_y + y_res[i])
                if "ego_yaw" in rows[i]:
                    rows[i]["ego_yaw"] = "{:.6f}".format(yaw_res[i])
                if "steer" in rows[i]:
                    rows[i]["steer"] = "{:.6f}".format(steer_res[i])
            lateral_source = "driver_residual_pool"
        else:
            lateral_source = "original_rows"

        with open(out_fp, "w", encoding="utf-8", newline="") as f:
            w = csv.DictWriter(f, fieldnames=fieldnames)
            w.writeheader()
            for r in rows:
                w.writerow(r)

        summary.append(
            {
                "source_file": rel,
                "out_file": os.path.relpath(out_fp, args.out_dir).replace("\\", "/"),
                "n_rows": str(len(rows)),
                "n_pred_rows": str(n_pred),
                "driver_id": _extract_driver_id(fp),
                "lateral_source": lateral_source,
            }
        )

    sum_fp = os.path.join(args.out_dir, "generation_summary.csv")
    with open(sum_fp, "w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(
            f,
            fieldnames=[
                "source_file",
                "out_file",
                "n_rows",
                "n_pred_rows",
                "driver_id",
                "lateral_source",
            ],
        )
        w.writeheader()
        for r in summary:
            w.writerow(r)

    print("[OK] generated files:", len(summary))
    print("[OK] summary:", sum_fp)


if __name__ == "__main__":
    main()

